[package]
name = "jetty"
version = "0.2.0"
authors = ["Andreas Maier <andreas.martin.maier@desy.de>"]
edition = "2021"
description = "Jet clustering"
readme = "Readme.md"
license = "GPL-3.0-or-later"
keywords = ["physics", "jets"]
categories = ["science"]
repository = "https://github.com/a-maier/jetty"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noisy_float = "0.2"
log = "0.4"

[dev-dependencies]
env_logger = "0.10"
